### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by dufferzafar** [dufferzafar/github-analytics#1]
- [ ] Add charts to readme
- [ ] Merge initial & final doc
- [ ] Update PDF's title
- [ ] Upload to ArXiv
